# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13eb92a4e4356d1efe26f70803599d9711da67ce664e855e0acc65588151aabad902ed624f949f0234ba58fe24083d8800307da1cb8ea8ca8fbffdac5e542971

test:
  secret_key_base: 2e0314fc0c58035685bfbd42a26dc8a126e9842c7a45a35c83279ba7435fad8b86903239f02b154dcb5b12abfd0f6c968655870477fbb9f1322705eac6fe6b4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
